config/routes.rb
Twitterscape::Application.routes.draw do
  resources :twitter_credentials

  match 'home/index(.:format)'

  root to: "home#index"

end

app/models/twitter_credential.rb
class TwitterCredential < ActiveRecord::Base
  attr_accessible :consumer_key, :consumer_secret, :oauth_token, :oauth_token_secret
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
require_dependency 'tweet_pile'

class HomeController < ApplicationController
  def list_friends
    friend_ids = Twitter.friend_ids.map(&:to_i)
    @friends = Twitter.users(friend_ids, method: :get)
  end

  def index
    @tweets = Rails.cache.fetch("tweets", expires_in: 2.minutes) do
      Twitter.home_timeline(count: 40, include_entities: true)
    end

    piles = @tweets.group_by(&:from_user)

    @piles = piles.map { |name, tweets| TweetPile.new(name, tweets) }.sort
  end
end

app/controllers/twitter_credentials_controller.rb
class TwitterCredentialsController < ApplicationController
  # GET /twitter_credentials
  # GET /twitter_credentials.json
  def index
    @twitter_credentials = TwitterCredential.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @twitter_credentials }
    end
  end

  # GET /twitter_credentials/1
  # GET /twitter_credentials/1.json
  def show
    @twitter_credential = TwitterCredential.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @twitter_credential }
    end
  end

  # GET /twitter_credentials/new
  # GET /twitter_credentials/new.json
  def new
    @twitter_credential = TwitterCredential.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @twitter_credential }
    end
  end

  # GET /twitter_credentials/1/edit
  def edit
    @twitter_credential = TwitterCredential.find(params[:id])
  end

  # POST /twitter_credentials
  # POST /twitter_credentials.json
  def create
    @twitter_credential = TwitterCredential.new(params[:twitter_credential])

    respond_to do |format|
      if @twitter_credential.save
        format.html { redirect_to @twitter_credential, notice: 'Twitter credential was successfully created.' }
        format.json { render json: @twitter_credential, status: :created, location: @twitter_credential }
      else
        format.html { render action: "new" }
        format.json { render json: @twitter_credential.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /twitter_credentials/1
  # PUT /twitter_credentials/1.json
  def update
    @twitter_credential = TwitterCredential.find(params[:id])

    respond_to do |format|
      if @twitter_credential.update_attributes(params[:twitter_credential])
        format.html { redirect_to @twitter_credential, notice: 'Twitter credential was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @twitter_credential.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twitter_credentials/1
  # DELETE /twitter_credentials/1.json
  def destroy
    @twitter_credential = TwitterCredential.find(params[:id])
    @twitter_credential.destroy

    respond_to do |format|
      format.html { redirect_to twitter_credentials_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/twitter_credentials_helper.rb
module TwitterCredentialsHelper
end

app/views/home/index.html.erb
<h1>@worldnamer: refreshed <%= Time.now.strftime("%H:%M") %></h1>
<div id="home">
  <% @piles.each do |pile| %>
  <div id="<%= pile.name %>" class="tweet_pile">
  	<div class="twitter_handle"><%= pile.name %></div>
    <div class="tweets">
    	<ul>
        <% pile.tweets.each do |tweet| %>
        <li class='<%= tweet.age %>'><%= tweet.full_text.html_safe %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <% end %>
</div>

app/views/home/index.json.erb
{"piles": <%= 
  @piles.map do |pile|
    {
      name: pile.name,
      tweets: pile.tweets.map { |tweet| {age: tweet.age, full_text: tweet.full_text} }
    }
  end.to_json.html_safe
%>}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitterscape</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta http-equiv="refresh" content="120;url=/">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/twitter_credentials/_form.html.erb
<%= form_for(@twitter_credential) do |f| %>
  <% if @twitter_credential.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@twitter_credential.errors.count, "error") %> prohibited this twitter_credential from being saved:</h2>

      <ul>
      <% @twitter_credential.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :consumer_key %><br />
    <%= f.text_field :consumer_key %>
  </div>
  <div class="field">
    <%= f.label :consumer_secret %><br />
    <%= f.text_field :consumer_secret %>
  </div>
  <div class="field">
    <%= f.label :oauth_token %><br />
    <%= f.text_field :oauth_token %>
  </div>
  <div class="field">
    <%= f.label :oauth_token_secret %><br />
    <%= f.text_field :oauth_token_secret %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/twitter_credentials/edit.html.erb
<h1>Editing twitter_credential</h1>

<%= render 'form' %>

<%= link_to 'Show', @twitter_credential %> |
<%= link_to 'Back', twitter_credentials_path %>

app/views/twitter_credentials/index.html.erb
<h1>Listing twitter_credentials</h1>

<table>
  <tr>
    <th>Consumer key</th>
    <th>Consumer secret</th>
    <th>Oauth token</th>
    <th>Oauth token secret</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @twitter_credentials.each do |twitter_credential| %>
  <tr>
    <td><%= twitter_credential.consumer_key %></td>
    <td><%= twitter_credential.consumer_secret %></td>
    <td><%= twitter_credential.oauth_token %></td>
    <td><%= twitter_credential.oauth_token_secret %></td>
    <td><%= link_to 'Show', twitter_credential %></td>
    <td><%= link_to 'Edit', edit_twitter_credential_path(twitter_credential) %></td>
    <td><%= link_to 'Destroy', twitter_credential, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Twitter credential', new_twitter_credential_path %>

app/views/twitter_credentials/new.html.erb
<h1>New twitter_credential</h1>

<%= render 'form' %>

<%= link_to 'Back', twitter_credentials_path %>

app/views/twitter_credentials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Consumer key:</b>
  <%= @twitter_credential.consumer_key %>
</p>

<p>
  <b>Consumer secret:</b>
  <%= @twitter_credential.consumer_secret %>
</p>

<p>
  <b>Oauth token:</b>
  <%= @twitter_credential.oauth_token %>
</p>

<p>
  <b>Oauth token secret:</b>
  <%= @twitter_credential.oauth_token_secret %>
</p>


<%= link_to 'Edit', edit_twitter_credential_path(@twitter_credential) %> |
<%= link_to 'Back', twitter_credentials_path %>